#!/usr/bin/env bash
# Install the load balanecer
sudo apt-get -y update
sudo apt-get -y install haproxy
echo 'ENABLED=1' >> /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg .
cat >> /etc/haproxy/haproxy.cfg << CONFIG
frontend front
	bind *:80
	mode http
	default_backend back
backend back
    balance roundrobin
    server 48713-web-01 54.160.81.90 check
    server 48713-web-02 54.167.184.6:80 check
CONFIG
sudo service haproxy restart
