#!/usr/bin/env bash
# Bash script that uses ssh to connect to your server using the private key ~/.ssh/school with the user ubuntu.
# ssh-keygen -t rsa -b 4096 -f school -N betty
ssh-keygen -f ~/.ssh/school -b 4096 -N betty
